<?php
/**
 * 后台中文基线语言包：随内核发布，作为所有语言的最终降级方案，禁止删除
 * 键规范：admin.{模块}.{语义}；下划线前缀键（_name/_locale）为包元信息
 */
defined('APP_BOOT') or exit;

return array(
    '_name'   => '中文（简体）',
    '_locale' => 'zh-CN',

    /* ---------- 通用（布局/按钮/提示） ---------- */
    'admin.common.admin_title'   => '后台管理',
    'admin.common.admin_panel'   => '管理后台',
    'admin.common.view_site'     => '查看站点',
    'admin.common.toggle_nav'    => '切换导航菜单',
    'admin.common.darkmode'      => '明暗切换',
    'admin.common.darkmode_tip'  => '切换明暗模式',
    'admin.common.save'          => '保存',
    'admin.common.delete'        => '删除',
    'admin.common.edit'          => '编辑',
    'admin.common.confirm'       => '确定',
    'admin.common.cancel'        => '取消',
    'admin.common.search'        => '搜索',
    'admin.common.reset'         => '重置',
    'admin.common.submit'        => '提交',
    'admin.common.upload'        => '上传',
    'admin.common.back'          => '返回',
    'admin.common.actions'       => '操作',
    'admin.common.status'        => '状态',
    'admin.common.created_at'    => '创建时间',
    'admin.common.none'          => '暂无数据',
    'admin.common.page_prev'     => '上一页',
    'admin.common.page_next'     => '下一页',
    'admin.common.all'           => '全部',
    'admin.common.yes'           => '是',
    'admin.common.no'            => '否',
    'admin.common.enabled'       => '启用',
    'admin.common.disabled'      => '禁用',
    'admin.common.on'            => '开',
    'admin.common.off'           => '关',
    'admin.common.tips'          => '提示',
    'admin.common.delete_confirm'=> '确定删除吗？此操作不可恢复',
    'admin.common.saved'         => '已保存',
    'admin.common.deleted'       => '已删除',
    'admin.common.failed'        => '操作失败',
    'admin.common.success'       => '操作成功',

    /* ---------- 侧边菜单 ---------- */
    'admin.menu.dashboard'        => '仪表盘',
    'admin.menu.post'             => '文章管理',
    'admin.menu.comment'          => '评论管理',
    'admin.menu.category'         => '分类管理',
    'admin.menu.user'             => '用户管理',
    'admin.menu.setting_site'     => '站点设置',
    'admin.menu.setting_nav'      => '导航管理',
    'admin.menu.setting_security' => '安全设置',
    'admin.menu.theme'            => '模板管理',
    'admin.menu.plugin'           => '插件管理',
    'admin.menu.plugin_group'     => '插件',
    'admin.menu.log'              => '日志中心',
    'admin.menu.profile'          => '个人资料',

    /* ---------- 登录/会话 ---------- */
    'admin.auth.logout'       => '登出',
    'admin.auth.pwd_expired'  => '密码已过期，请先修改密码',
    // 以下 8 键对应 Auth::msgOf 机器码（服务层只产出机器码，显示层按域映射）
    'admin.auth.pwd_len'          => '密码长度必须为 8-64 位',
    'admin.auth.pwd_classes'      => '密码必须包含大写字母、小写字母、数字、特殊字符中的至少三类',
    'admin.auth.pwd_contain_name' => '密码中不得包含用户名',
    'admin.auth.pwd_weak'         => '密码过于简单，命中弱口令黑名单',
    'admin.auth.user_not_found'   => '用户不存在',
    'admin.auth.old_password_wrong' => '原密码错误',
    'admin.auth.pwd_history_hit'  => '新密码不能与最近 %s 次密码相同',
    'admin.auth.pwd_changed'      => '密码修改成功',

    /* ---------- zip 上传链路（对应 ZipSafe::msgOf 机器码） ---------- */
    'admin.zipsafe.upload_server_limit'   => '文件超过服务器上传限制（约 %sMB）',
    'admin.zipsafe.upload_no_file'        => '请选择要上传的 zip 文件（错误码 %s）',
    'admin.zipsafe.zip_too_large'         => 'zip 文件不得超过 %sMB',
    'admin.zipsafe.zip_ext_only'          => '仅支持 .zip 格式',
    'admin.zipsafe.zip_no_ziparchive'     => '服务器未启用 ZipArchive 扩展，无法解压 zip 包',
    'admin.zipsafe.zip_open_failed'       => 'zip 文件无法打开',
    'admin.zipsafe.zip_illegal_path'      => 'zip 包含非法路径条目',
    'admin.zipsafe.zip_entry_denied'      => 'zip 包含不允许的条目：%s',
    'admin.zipsafe.zip_entry_type_denied' => 'zip 包含不允许的条目类型（符号链接等）：%s',
    'admin.zipsafe.zip_missing_required'  => 'zip 包缺少必需的文件',
    'admin.zipsafe.zip_extract_failed'    => 'zip 解压失败',
    'admin.zipsafe.dest_create_failed'    => '目标目录创建失败',
    'admin.zipsafe.backup_failed'         => '旧目录备份失败，已中止覆盖',
    'admin.zipsafe.swap_failed'           => '新目录替换失败，已回滚',

    /* ---------- 站点/安全/导航设置 ---------- */
    'admin.setting.site_name'              => '站点名称',
    'admin.setting.site_motto'             => '一句话座右铭',
    'admin.setting.site_desc'              => '站点描述（SEO）',
    'admin.setting.site_keywords'          => '关键词（SEO，逗号分隔）',
    'admin.setting.per_page'               => '每页文章条数（1-50）',
    'admin.setting.timezone'               => '站点时区（影响日志、文章、评论等全部时间显示）',
    'admin.setting.admin_locale'           => '后台语言',
    'admin.setting.admin_locale_hint'      => '语言包置于 assets/langs/ 目录，放入后此处自动可选；缺失文案自动回退中文',
    'admin.setting.register_disabled'      => '关闭公开注册',
    'admin.setting.register_disabled_hint' => '勾选后前台注册页不可访问，新用户只能由后台创建',
    'admin.setting.post_audit'             => '开启文章审核',
    'admin.setting.post_audit_hint'        => '开启后仅管理员可直接发布，投稿进入待审核',
    'admin.setting.comment_audit'          => '开启评论审核',
    'admin.setting.comment_audit_hint'     => '开启后评论须管理员审核后才公开',
    'admin.setting.rewrite'                => '启用伪静态',
    'admin.setting.rewrite_hint'           => '需服务器已配置 rewrite 规则，见 README',
    'admin.setting.site_saved'             => '站点设置已保存',
    'admin.setting.security_saved'         => '安全设置已保存',
    'admin.setting.nav_saved'              => '导航项已保存',
    'admin.setting.nav_fresh_empty_url'    => '新添加的导航项必须填写链接',
    'admin.setting.tz.asia_shanghai'       => '中国标准时间（UTC+8）',
    'admin.setting.tz.asia_hong_kong'      => '香港（UTC+8）',
    'admin.setting.tz.asia_taipei'         => '台北（UTC+8）',
    'admin.setting.tz.asia_singapore'      => '新加坡（UTC+8）',
    'admin.setting.tz.asia_tokyo'          => '日本（UTC+9）',
    'admin.setting.tz.asia_seoul'          => '韩国（UTC+9）',
    'admin.setting.tz.asia_bangkok'        => '泰国（UTC+7）',
    'admin.setting.tz.asia_kolkata'        => '印度（UTC+5:30）',
    'admin.setting.tz.asia_dubai'          => '迪拜（UTC+4）',
    'admin.setting.tz.europe_london'       => '英国（UTC+0/+1）',
    'admin.setting.tz.europe_paris'        => '法国/德国（UTC+1/+2）',
    'admin.setting.tz.europe_athens'       => '希腊（UTC+2/+3）',
    'admin.setting.tz.europe_moscow'       => '莫斯科（UTC+3）',
    'admin.setting.tz.america_new_york'    => '美东（UTC-5/-4）',
    'admin.setting.tz.america_chicago'     => '美中（UTC-6/-5）',
    'admin.setting.tz.america_denver'      => '美山地（UTC-7/-6）',
    'admin.setting.tz.america_los_angeles' => '美西（UTC-8/-7）',
    'admin.setting.tz.america_sao_paulo'   => '巴西（UTC-3）',
    'admin.setting.tz.australia_sydney'    => '悉尼（UTC+10/+11）',
    'admin.setting.tz.pacific_auckland'    => '新西兰（UTC+12/+13）',
    'admin.setting.tz.utc'                 => '协调世界时（UTC+0）',

    /* ---------- 仪表盘 ---------- */
    'admin.dashboard.greeting_morning'      => '%s，早上好！',
    'admin.dashboard.greeting_noon'         => '%s，中午好！',
    'admin.dashboard.greeting_night'        => '%s，晚上好！',
    'admin.dashboard.welcome'               => '欢迎访问%s',
    'admin.dashboard.stat_posts'            => '文章总数',
    'admin.dashboard.stat_published'        => '已发布',
    'admin.dashboard.stat_pending_posts'    => '待审核文章',
    'admin.dashboard.stat_comments'         => '已公开评论',
    'admin.dashboard.stat_pending_comments' => '待审评论',
    'admin.dashboard.stat_users'            => '注册用户',
    'admin.dashboard.recent_logs'           => '最近审计日志',
    'admin.dashboard.goto_logs'             => '进入日志中心',

    /* ---------- 日志 ---------- */
    'admin.log.col_time'     => '时间',
    'admin.log.col_user'     => '用户',
    'admin.log.col_category' => '类别',
    'admin.log.col_action'   => '动作',
    'admin.log.col_result'   => '结果',
    'admin.log.success'      => '成功',
    'admin.log.fail'         => '失败',

    /* ---------- 文章 ---------- */
    'admin.post.status_published' => '已发布',
    'admin.post.status_pending'   => '待审核',
    'admin.post.status_draft'     => '草稿',
    'admin.post.status_trash'     => '回收站',
    'admin.post.type_all'         => '全部内容',
    'admin.post.type_post'        => '文章',
    'admin.post.type_page'        => '页面',
    'admin.post.add'              => '新增文章',
    'admin.post.col_title'        => '标题',
    'admin.post.col_author'       => '作者',
    'admin.post.col_category'     => '分类',
    'admin.post.col_views'        => '浏览',
    'admin.post.col_updated'      => '更新时间',
    'admin.post.badge_page'       => '页面',
    'admin.post.badge_top'        => '置顶',
    'admin.post.approve'          => '通过',
    'admin.post.reject'           => '驳回',
    'admin.post.pin'              => '置顶',
    'admin.post.unpin'            => '取消置顶',
    'admin.post.restore'          => '恢复',
    'admin.post.destroy'          => '彻底删除',
    'admin.post.destroy_confirm'  => '彻底删除后不可恢复，确认？',
    'admin.post.trash_confirm'    => '确认移入回收站？',
    'admin.post.edit_title'       => '编辑文章',
    'admin.post.opt_publish'      => '发布',
    'admin.post.opt_submit_review'=> '提交审核',
    'admin.post.field_title'      => '标题',
    'admin.post.field_slug'       => '别名，不能为纯数字',
    'admin.post.uncategorized'    => '未分类',
    'admin.post.as_page'          => '作为独立页面（不出现在文章列表）',
    'admin.post.show_in_nav'      => '显示在侧边栏导航',
    'admin.post.audit_hint'       => '站点已开启文章审核：提交的文章需管理员审核通过后才会发布。',
    'admin.post.field_content'    => '正文（Markdown）',
    'admin.post.field_excerpt'    => '摘要（可选，留空自动截取）',
    'admin.post.field_cover'      => '封面图（仅可通过上传更换，支持 jpg/png/webp/gif，不超过 2MB）',
    'admin.post.cover_preview'    => '封面预览',
    'admin.post.cover_upload'     => '上传封面',
    'admin.post.top_only_published' => '仅已发布文章可置顶',
    'admin.post.top_done'         => '已置顶，前台列表将优先展示',
    'admin.post.top_canceled'     => '已取消置顶',
    'admin.post.not_found'        => '文章不存在',
    'admin.post.title_required'   => '标题不能为空',
    'admin.post.cover_invalid'    => '封面路径非法（仅允许 uploads/ 目录下的图片）',
    'admin.post.slug_numeric'     => '别名（slug）不能为纯数字，避免与文章 ID 访问冲突',
    'admin.post.slug_taken'       => '别名（slug）已被占用',
    'admin.post.saved'            => '保存成功',
    'admin.post.trashed'          => '已移入回收站',
    'admin.post.restored'         => '已恢复为草稿',
    'admin.post.destroyed'        => '已彻底删除',
    'admin.post.approved'         => '已通过并发布',
    'admin.post.rejected'         => '已驳回为草稿',

    /* ---------- 上传 ---------- */
    'admin.upload.failed'   => '上传失败',
    'admin.upload.cover_ok' => '封面上传成功',

    /* ---------- 评论 ---------- */
    'admin.comment.status_published' => '已公开',
    'admin.comment.status_pending'   => '待审核',
    'admin.comment.status_trash'     => '回收站',
    'admin.comment.filter_author'    => '作者用户名/昵称或 ID',
    'admin.comment.filter_post_id'   => '文章 ID',
    'admin.comment.filter_date_range'=> '发表时间范围',
    'admin.comment.filter_btn'       => '筛选',
    'admin.comment.total'            => '共 %s 条评论。',
    'admin.comment.col_content'      => '内容',
    'admin.comment.col_post'         => '所属文章',
    'admin.comment.approved'         => '评论已通过',
    'admin.comment.rejected'         => '评论已驳回',
    'admin.comment.trashed'          => '评论已移入回收站',
    'admin.comment.restored'         => '评论已恢复',
    'admin.comment.restored_pending' => '评论已恢复，待审核通过后发布',

    /* ---------- 分类 ---------- */
    'admin.category.add'            => '新增分类',
    'admin.category.name'           => '名称',
    'admin.category.slug'           => '中文释义（slug）',
    'admin.category.description'    => '描述',
    'admin.category.sort'           => '排序',
    'admin.category.add_btn'        => '添加',
    'admin.category.col_edit'       => '编辑（名称 / slug / 描述 / 排序）',
    'admin.category.delete_confirm' => '确认删除该分类？',
    'admin.category.name_required'  => '分类名称不能为空',
    'admin.category.slug_required'  => 'slug 不能为空（仅限小写字母、数字、连字符）',
    'admin.category.slug_taken'     => 'slug 已被占用',
    'admin.category.in_use'         => '该分类下仍有 %s 篇文章，请先移动文章后再删除',
    'admin.category.deleted'        => '分类已删除',

    /* ---------- 用户 ---------- */
    'admin.user.add'                   => '新增用户',
    'admin.user.edit_title'            => '编辑用户',
    'admin.user.role_admin'            => '管理员',
    'admin.user.role_editor'           => '编辑',
    'admin.user.role_user'             => '用户',
    'admin.user.col_username'          => '用户名',
    'admin.user.col_nickname'          => '昵称',
    'admin.user.col_email'             => '邮箱',
    'admin.user.col_phone'             => '手机',
    'admin.user.col_role'              => '角色',
    'admin.user.col_locked'            => '锁定',
    'admin.user.col_registered'        => '注册时间',
    'admin.user.me'                    => '（我）',
    'admin.user.status_ok'             => '正常',
    'admin.user.status_disabled'       => '已禁用',
    'admin.user.status_banned'         => '已封禁',
    'admin.user.status_deleted'        => '已注销',
    'admin.user.opt_disabled'          => '禁用',
    'admin.user.locked_until'          => '锁定至 %s',
    'admin.user.unlock'                => '解锁',
    'admin.user.ban'                   => '封禁',
    'admin.user.unban'                 => '解封',
    'admin.user.deregister'            => '注销',
    'admin.user.ban_confirm'           => '封禁后该用户将无法登录，确认封禁？',
    'admin.user.deregister_confirm'    => '注销后该用户无法登录，其文章与评论将显示为“用户已注销”，确认注销？',
    'admin.user.field_username_new'    => '用户名（3-32 位字母/数字/下划线）',
    'admin.user.field_email'           => '邮箱（可空）',
    'admin.user.field_phone'           => '手机号（可空）',
    'admin.user.field_role'            => '角色（editor/admin 仅可由管理员在此授予）',
    'admin.user.root_no_demote'        => '（安装管理员，不可降权）',
    'admin.user.field_status'          => '账号状态',
    'admin.user.field_new_password'    => '重置密码（留空则不修改；8-64 位、大小写/数字/特殊字符至少三类）',
    'admin.user.field_current_password'=> '您的当前密码（重置密码或修改邮箱/手机时必填，敏感操作重验）',
    'admin.user.create_tip'            => '新建用户将自动生成随机初始密码，保存后仅展示一次。',
    'admin.user.force_change'          => '下次登录强制改密（配合“密码定期更换”策略使用）',
    'admin.user.not_found'             => '用户不存在',
    'admin.user.username_format'       => '用户名须为 3-32 位字母、数字或下划线',
    'admin.user.username_taken'        => '用户名已被占用',
    'admin.user.email_taken'           => '邮箱已被占用',
    'admin.user.phone_taken'           => '该手机号已被占用',
    'admin.user.gen_pwd_error'         => '初始密码生成异常：%s',
    'admin.user.concurrent_conflict'   => '用户名/邮箱/手机号已被占用（并发冲突），请重试',
    'admin.user.created_with_pwd'      => '用户已创建。初始密码（仅显示一次，请通过安全渠道告知用户）：%s',
    'admin.user.operator_pwd_required' => '重置密码或修改邮箱/手机须填写您（操作者）的当前密码',
    'admin.user.self_protect'          => '不能禁用或变更自己的角色',
    'admin.user.root_protect'          => '安装管理员账号不可降权或禁用',
    'admin.user.last_admin'            => '系统至少需要保留一位管理员',
    'admin.user.saved_pwd_reset'       => '用户已保存，密码已重置',
    'admin.user.saved'                 => '用户已保存',
    'admin.user.unlocked'              => '已解除锁定',
    'admin.user.self_ban'              => '不能封禁自己',
    'admin.user.root_ban'              => '安装管理员账号不可封禁',
    'admin.user.last_admin_avail'      => '系统至少需要保留一位可用管理员',
    'admin.user.banned'                => '已封禁该用户，其将无法登录',
    'admin.user.unbanned'              => '已解除封禁',
    'admin.user.self_deregister'       => '不能注销自己',
    'admin.user.root_deregister'       => '安装管理员账号不可注销',
    'admin.user.deregistered'          => '已注销该用户，其历史内容将以“用户已注销”匿名展示',
    'admin.user.restored'              => '已恢复该用户',

    /* ---------- 导航管理 ---------- */
    // help 含 <code> 标签（可信的内核语言包），视图不转义直接输出
    'admin.nav.help'              => '拖动行首手柄图标调整顺序，导航项按保存顺序展示在前台主题导航中。支持一层父子层级：把某行的「父级」选为另一行，该行即归入其下成为子项（父级须为更早的顶层行）；拖动不会改变父子从属关系（子项不能拖到其父项上方）。新添加的项必须填写链接；既有顶层项的链接之后可留空作纯文本分组标签（仅在它有子项时生效），子项链接必填。点击「添加导航项」追加新行，已有顶层项时可直接为其选择父级；行尾红色按钮移除该行，父项被移除时其子项提升为顶层。所有改动点击「保存」后生效。链接支持站内相对路径（如 <code>/index.php?r=page/about</code>）或 http(s) 地址。',
    'admin.nav.drag'              => '拖动排序',
    'admin.nav.top'               => '顶层',
    'admin.nav.remove_row'        => '移除该行',
    'admin.nav.empty'             => '暂无自定义导航项，点击下方按钮添加。',
    'admin.nav.new_title'         => '新增导航标题（留空不新增）',
    'admin.nav.new_url'           => '新增链接，如 /index.php?r=page/about',
    'admin.nav.new_badge'         => '新增（顶层）',
    'admin.nav.add_btn'           => '添加导航项',
    'admin.nav.child_url_required'=> '子项链接必填',
    'admin.nav.top_url_optional'  => '顶层可留空作分组标签',
    'admin.nav.new_url_required'  => '链接（必填），如 /index.php?r=page/about',

    /* ---------- 安全设置 ---------- */
    'admin.security.tip'                 => '以下默认值为等保二级安全水位，随意调低将削弱系统安全性。所有变更均会写入审计日志。',
    'admin.security.group_login'         => '登录与会话',
    'admin.security.group_password'      => '口令策略',
    'admin.security.group_ip'            => '客户端 IP',
    'admin.security.group_log'           => '审计日志',
    'admin.security.group_debug'         => '调试',
    'admin.security.login_max_fail'      => '连续登录失败锁定阈值（次，默认 5）',
    'admin.security.lock_minutes'        => '锁定时长（分钟，默认 10）',
    'admin.security.session_timeout'     => '会话无操作超时（分钟，默认 30）',
    'admin.security.pwd_expire'          => '启用密码定期更换',
    'admin.security.pwd_expire_hint'     => '默认关闭；开启后超期登录将被强制改密',
    'admin.security.pwd_expire_days'     => '密码有效期（天，30-365，默认 90）',
    'admin.security.pwd_history'         => '密码历史防重复次数（0 表示关闭，默认 0）',
    'admin.security.ip_header'           => '从自定义标头读取客户端 IP',
    'admin.security.ip_header_hint'      => '默认关闭',
    'admin.security.ip_header_name'      => '标头名称（支持多个，英文逗号分隔，在前优先级高；如 ali-real-client-ip,X-Forwarded-For）',
    'admin.security.ip_header_name_hint' => '按顺序依次尝试，某个标头取到合法 IP 即停止；均取不到时使用 REMOTE_ADDR。',
    'admin.security.ip_warn'             => '警告：仅在站点部署于可信反向代理/CDN 之后才可开启此项。若服务器直接暴露公网却信任 X-Forwarded-For 等标头，攻击者可伪造 IP 绕过限流与审计。',
    'admin.security.log_retention'       => '日志留存天数（下限 180 天，默认 180）',
    'admin.security.debug'               => '调试模式',
    'admin.security.debug_hint'          => '生产环境必须关闭；开启后错误详情会输出到页面',

    /* ---------- 模板管理 ---------- */
    'admin.theme.upload_title'      => '上传主题（zip，须含 style.css）',
    'admin.theme.col_dir'           => '主题',
    'admin.theme.col_version'       => '版本',
    'admin.theme.empty'             => '未发现任何主题',
    'admin.theme.active'            => '启用中',
    'admin.theme.inactive'          => '未启用',
    'admin.theme.configure'         => '设置',
    'admin.theme.delete_confirm'    => '确认删除该主题？此操作不可恢复',
    'admin.theme.not_found'         => '主题不存在',
    'admin.theme.activated'         => '已启用主题：%s',
    'admin.theme.not_deletable'     => '该主题不可删除',
    'admin.theme.cannot_delete_active' => '不能删除当前启用的主题',
    'admin.theme.deleted'           => '主题已删除',
    'admin.theme.dir_missing'       => '主题目录不存在',
    'admin.theme.setting_page'      => '主题设置',
    'admin.theme.setting_title'     => '主题设置：%s（%s）',
    'admin.theme.no_schema'         => '该主题未提供设置清单（主题目录内无 settings.php），没有可配置项。',
    'admin.theme.setting_saved'     => '主题设置已保存',
    'admin.theme.zip_required'      => '请选择要上传的 zip 文件',
    'admin.theme.zip_too_large'     => 'zip 文件不得超过 10MB',
    'admin.theme.zip_only'          => '仅支持 .zip 格式',
    'admin.theme.zip_ext_missing'   => '服务器未启用 ZipArchive 扩展，无法解压主题包',
    'admin.theme.dir_invalid'       => '主题目录名非法或为保留主题',
    'admin.theme.zip_open_failed'   => 'zip 文件无法打开',
    'admin.theme.zip_bad_path'      => 'zip 包含非法路径条目',
    'admin.theme.zip_bad_entry'     => 'zip 包含不允许的条目：%s',
    'admin.theme.zip_no_style'      => '主题包缺少 style.css',
    'admin.theme.dir_create_failed' => '主题目录创建失败',
    'admin.theme.zip_extract_failed'=> 'zip 解压失败',
    'admin.theme.uploaded'          => '主题已上传：%s',
    'admin.theme.updated'           => '主题已覆盖更新：%s',
    'admin.theme.no_overwrite_active' => '不能覆盖更新当前启用的主题，请先切换到其他主题',
    'admin.theme.name_mismatch'     => '包内 Theme Name 与现有主题不一致，已拒绝覆盖',
    'admin.theme.upload_tip'        => '同名主题将执行覆盖更新（旧目录自动备份、失败回滚）；启用中的主题与 default 不可覆盖。服务器上传上限约 %sMB，程序限制 10MB。',

    /* ---------- 插件管理 ---------- */
    'admin.plugin.orphan_tip'        => '以下插件的目录已不存在（可能被直接删除而非经后台卸载），但其配置与数据仍残留在数据库中：',
    'admin.plugin.orphan_confirm'    => '确认清理该插件的全部残留数据？此操作不可恢复',
    'admin.plugin.orphan_btn'        => '清理残留数据',
    'admin.plugin.col_name'          => '插件',
    'admin.plugin.empty'             => '未发现任何插件',
    'admin.plugin.active'            => '已启用',
    'admin.plugin.inactive'          => '已禁用',
    'admin.plugin.delete_confirm'    => '确认删除该插件？此操作不可恢复',
    'admin.plugin.orphan_none'       => '该插件无需清理或目录仍存在',
    'admin.plugin.orphan_cleaned'    => '残留数据已清理：%s',
    'admin.plugin.activate_failed'   => '插件不存在或启用失败',
    'admin.plugin.activated'         => '插件已启用',
    'admin.plugin.deactivate_failed' => '插件未启用或不存在',
    'admin.plugin.deactivated'       => '插件已禁用',
    'admin.plugin.uninstall_failed'  => '插件不存在或删除失败',
    'admin.plugin.uninstalled'       => '插件已删除',
    'admin.plugin.zip_required'      => '请选择要上传的 zip 文件',
    'admin.plugin.zip_no_main'       => '插件包内未找到主文件（{slug}.php）',
    'admin.plugin.main_file_invalid' => '包内未找到合法插件主文件（{slug}.php 且头部须声明 Plugin Name）',
    'admin.plugin.name_mismatch'     => '包内 Plugin Name 与现有插件不一致，已拒绝覆盖',
    'admin.plugin.uploaded'          => '插件已上传：%s',
    'admin.plugin.updated'           => '插件已覆盖更新：%s',
    'admin.plugin.upload_title'      => '上传插件（zip，包内须含 {slug}.php 主文件并声明 Plugin Name）',
    'admin.plugin.upload_tip'        => '同名插件将执行覆盖更新（旧目录自动备份、失败回滚）；服务器上传上限约 %sMB，程序限制 10MB。',

    /* ---------- 日志中心（补充） ---------- */
    'admin.log.all_categories'  => '全部类别',
    'admin.log.all_results'     => '全部结果',
    'admin.log.keyword_ph'      => '动作关键词',
    'admin.log.date_range_ph'   => '开始日期 ~ 结束日期',
    'admin.log.export_confirm'  => '导出审计日志前须填写当前登录密码，确认继续？',
    'admin.log.export_pwd_ph'   => '当前密码（导出需重验）',
    'admin.log.export_btn'      => '导出 CSV',
    'admin.log.total'           => '共 %s 条记录。',
    'admin.log.col_operator'    => '操作者',
    'admin.log.col_detail'      => '详情',
    'admin.log.csv_user_id'     => '用户ID',
    'admin.log.export_pwd_wrong'=> '导出审计日志须填写正确的当前密码',

    /* ---------- 个人资料 ---------- */
    'admin.profile.basic'              => '基本资料',
    'admin.profile.signature'          => '个性签名（展示在作者页昵称下方，不超过 100 字，留空则不展示）',
    'admin.profile.email_code'         => '邮箱验证码（仅修改邮箱时需要）',
    'admin.profile.sms_code'           => '短信验证码（仅修改手机号时需要）',
    'admin.profile.send_code'          => '发送验证码',
    'admin.profile.avatar'             => '头像（仅可通过上传更换，支持 jpg/png/webp/gif，不超过 1MB）',
    'admin.profile.avatar_preview'     => '头像预览',
    'admin.profile.avatar_upload'      => '上传头像',
    'admin.profile.current_pwd'        => '当前密码（仅修改邮箱/手机时需要填写）',
    'admin.profile.change_pwd_card'    => '修改密码',
    'admin.profile.goto_change_pwd'    => '前往修改密码',
    'admin.profile.pwd_expired_notice' => '您的密码已过期，必须修改密码后才能继续使用后台。',
    'admin.profile.old_pwd'            => '当前密码',
    'admin.profile.new_pwd'            => '新密码（8-64 位；大写字母/小写字母/数字/特殊字符至少三类；不得含用户名）',
    'admin.profile.confirm_pwd'        => '确认新密码',
    'admin.profile.confirm_btn'        => '确认修改',
    'admin.profile.avatar_invalid'     => '头像路径非法',
    'admin.profile.pwd_required'       => '修改邮箱/手机须填写正确的当前密码',
    'admin.profile.email_code_wrong'   => '邮箱验证码错误或已过期',
    'admin.profile.sms_code_wrong'     => '短信验证码错误或已过期',
    'admin.profile.phone_taken'        => '该手机号已被其他账号使用',
    'admin.profile.saved'              => '资料已保存',
    'admin.profile.pwd_mismatch'       => '两次输入的新密码不一致',
    'admin.profile.pwd_changed'        => '密码修改成功',

    /* ---------- 上传（补充） ---------- */
    'admin.upload.image_size'     => '图片大小须在 2MB 以内',
    'admin.upload.avatar_size'    => '头像大小须在 1MB 以内',
    'admin.upload.no_file'        => '未收到文件',
    'admin.upload.error_code'     => '上传失败（错误码 %s）',
    'admin.upload.mime_whitelist' => '仅支持 jpg/png/webp/gif 图片',
    'admin.upload.dir_failed'     => '上传目录创建失败',
    'admin.upload.save_failed'    => '文件保存失败',
    'admin.upload.avatar_ok'      => '头像上传成功',

    /* ---------- JS 交互文案（后台注入 admin.js / verify.js / password_check.js / nav_sort.js） ---------- */
    'admin.js.confirm_title'      => '操作确认',
    'admin.js.confirm_ok'         => '确认',
    'admin.verify.fill_target'    => '请先填写邮箱或手机号',
    'admin.verify.network_error'  => '网络异常，请重试',
    'admin.verify.retry_in'       => '%s 秒后重发',
    'admin.pwd.need'              => '请输入新密码',
    'admin.pwd.len'               => '密码长度须为 8-64 位',
    'admin.pwd.classes'           => '密码须包含大写/小写/数字/特殊字符中的至少三类',
    'admin.pwd.contain_name'      => '密码不得包含用户名',
    'admin.pwd.repeat'            => '请再次输入新密码',
    'admin.pwd.mismatch'          => '两次输入的密码不一致',
    'admin.pwd.mismatch_live'     => '两次输入不一致',
    'admin.pwd.match_ok'          => '两次输入一致 ✓',
    'admin.nav.max_tip'           => '最多 %s 个导航项',
);
