<?php
/**
 * Admin language pack: English (US)
 * Keys mirror core/langs/zh_CN.php; missing keys fall back to the zh_CN baseline.
 */
defined('APP_BOOT') or exit;

return array(
    '_name'   => 'English (US)',
    '_locale' => 'en-US',

    /* ---------- Common (layout/buttons/labels) ---------- */
    'admin.common.admin_title'   => 'Administration',
    'admin.common.admin_panel'   => 'Admin Panel',
    'admin.common.view_site'     => 'View Site',
    'admin.common.toggle_nav'    => 'Toggle navigation',
    'admin.common.darkmode'      => 'Dark Mode',
    'admin.common.darkmode_tip'  => 'Toggle dark mode',
    'admin.common.save'          => 'Save',
    'admin.common.delete'        => 'Delete',
    'admin.common.edit'          => 'Edit',
    'admin.common.confirm'       => 'OK',
    'admin.common.cancel'        => 'Cancel',
    'admin.common.search'        => 'Search',
    'admin.common.reset'         => 'Reset',
    'admin.common.submit'        => 'Submit',
    'admin.common.upload'        => 'Upload',
    'admin.common.back'          => 'Back',
    'admin.common.actions'       => 'Actions',
    'admin.common.status'        => 'Status',
    'admin.common.created_at'    => 'Created At',
    'admin.common.none'          => 'No data',
    'admin.common.page_prev'     => 'Previous',
    'admin.common.page_next'     => 'Next',
    'admin.common.all'           => 'All',
    'admin.common.yes'           => 'Yes',
    'admin.common.no'            => 'No',
    'admin.common.enabled'       => 'Enable',
    'admin.common.disabled'      => 'Disable',
    'admin.common.on'            => 'On',
    'admin.common.off'           => 'Off',
    'admin.common.tips'          => 'Notice',
    'admin.common.delete_confirm'=> 'Are you sure? This cannot be undone.',
    'admin.common.saved'         => 'Saved',
    'admin.common.deleted'       => 'Deleted',
    'admin.common.failed'        => 'Operation failed',
    'admin.common.success'       => 'Operation succeeded',

    /* ---------- Sidebar menu ---------- */
    'admin.menu.dashboard'        => 'Dashboard',
    'admin.menu.post'             => 'Posts',
    'admin.menu.comment'          => 'Comments',
    'admin.menu.category'         => 'Categories',
    'admin.menu.user'             => 'Users',
    'admin.menu.setting_site'     => 'Site Settings',
    'admin.menu.setting_nav'      => 'Navigation',
    'admin.menu.setting_security' => 'Security',
    'admin.menu.theme'            => 'Themes',
    'admin.menu.plugin'           => 'Plugins',
    'admin.menu.plugin_group'     => 'Plugins',
    'admin.menu.log'              => 'Audit Logs',
    'admin.menu.profile'          => 'Profile',

    /* ---------- Auth/session ---------- */
    'admin.auth.logout'       => 'Log out',
    'admin.auth.pwd_expired'  => 'Your password has expired. Please change it first',
    // The following 8 keys map to Auth::msgOf machine codes
    'admin.auth.pwd_len'          => 'Password must be 8-64 characters',
    'admin.auth.pwd_classes'      => 'Password must contain at least 3 of: uppercase letters, lowercase letters, digits, special characters',
    'admin.auth.pwd_contain_name' => 'Password must not contain the username',
    'admin.auth.pwd_weak'         => 'Password is too simple (weak password blacklist hit)',
    'admin.auth.user_not_found'   => 'User not found',
    'admin.auth.old_password_wrong' => 'Current password is incorrect',
    'admin.auth.pwd_history_hit'  => 'New password cannot be the same as any of the last %s passwords',
    'admin.auth.pwd_changed'      => 'Password changed successfully',

    /* ---------- Zip upload pipeline (maps ZipSafe::msgOf machine codes) ---------- */
    'admin.zipsafe.upload_server_limit'   => 'File exceeds the server upload limit (approx. %sMB)',
    'admin.zipsafe.upload_no_file'        => 'Please select a zip file to upload (error code %s)',
    'admin.zipsafe.zip_too_large'         => 'Zip file must not exceed %sMB',
    'admin.zipsafe.zip_ext_only'          => 'Only .zip format is supported',
    'admin.zipsafe.zip_no_ziparchive'     => 'The ZipArchive extension is not enabled on the server; cannot extract zip packages',
    'admin.zipsafe.zip_open_failed'       => 'Unable to open the zip file',
    'admin.zipsafe.zip_illegal_path'      => 'The zip contains entries with illegal paths',
    'admin.zipsafe.zip_entry_denied'      => 'The zip contains a disallowed entry: %s',
    'admin.zipsafe.zip_entry_type_denied' => 'The zip contains a disallowed entry type (symlink etc.): %s',
    'admin.zipsafe.zip_missing_required'  => 'The zip package is missing a required file',
    'admin.zipsafe.zip_extract_failed'    => 'Failed to extract the zip',
    'admin.zipsafe.dest_create_failed'    => 'Failed to create the target directory',
    'admin.zipsafe.backup_failed'         => 'Failed to back up the old directory; overwrite aborted',
    'admin.zipsafe.swap_failed'           => 'Failed to move the new directory into place; rolled back',

    /* ---------- Site/security/nav settings ---------- */
    'admin.setting.site_name'              => 'Site Name',
    'admin.setting.site_motto'             => 'One-line Motto',
    'admin.setting.site_desc'              => 'Site Description (SEO)',
    'admin.setting.site_keywords'          => 'Keywords (SEO, comma-separated)',
    'admin.setting.per_page'               => 'Posts per page (1-50)',
    'admin.setting.timezone'               => 'Site timezone (affects all times: logs, posts, comments)',
    'admin.setting.admin_locale'           => 'Admin Language',
    'admin.setting.admin_locale_hint'      => 'Language packs live in assets/langs/; drop one in and it becomes selectable here. Missing strings fall back to Chinese.',
    'admin.setting.register_disabled'      => 'Disable Public Registration',
    'admin.setting.register_disabled_hint' => 'When checked, the front-end registration page is closed; new users can only be created in the admin',
    'admin.setting.post_audit'             => 'Enable Post Review',
    'admin.setting.post_audit_hint'        => 'When enabled, only admins can publish directly; submissions go to pending review',
    'admin.setting.comment_audit'          => 'Enable Comment Review',
    'admin.setting.comment_audit_hint'     => 'When enabled, comments are public only after admin approval',
    'admin.setting.rewrite'                => 'Enable Pretty URLs',
    'admin.setting.rewrite_hint'           => 'Requires rewrite rules configured on the server; see README',
    'admin.setting.site_saved'             => 'Site settings saved',
    'admin.setting.security_saved'         => 'Security settings saved',
    'admin.setting.nav_saved'              => 'Navigation saved',
    'admin.setting.nav_fresh_empty_url'    => 'Newly added navigation items must have a link',
    'admin.setting.tz.asia_shanghai'       => 'China Standard Time (UTC+8)',
    'admin.setting.tz.asia_hong_kong'      => 'Hong Kong (UTC+8)',
    'admin.setting.tz.asia_taipei'         => 'Taipei (UTC+8)',
    'admin.setting.tz.asia_singapore'      => 'Singapore (UTC+8)',
    'admin.setting.tz.asia_tokyo'          => 'Japan (UTC+9)',
    'admin.setting.tz.asia_seoul'          => 'Korea (UTC+9)',
    'admin.setting.tz.asia_bangkok'        => 'Thailand (UTC+7)',
    'admin.setting.tz.asia_kolkata'        => 'India (UTC+5:30)',
    'admin.setting.tz.asia_dubai'          => 'Dubai (UTC+4)',
    'admin.setting.tz.europe_london'       => 'United Kingdom (UTC+0/+1)',
    'admin.setting.tz.europe_paris'        => 'France/Germany (UTC+1/+2)',
    'admin.setting.tz.europe_athens'       => 'Greece (UTC+2/+3)',
    'admin.setting.tz.europe_moscow'       => 'Moscow (UTC+3)',
    'admin.setting.tz.america_new_york'    => 'US Eastern (UTC-5/-4)',
    'admin.setting.tz.america_chicago'     => 'US Central (UTC-6/-5)',
    'admin.setting.tz.america_denver'      => 'US Mountain (UTC-7/-6)',
    'admin.setting.tz.america_los_angeles' => 'US Pacific (UTC-8/-7)',
    'admin.setting.tz.america_sao_paulo'   => 'Brazil (UTC-3)',
    'admin.setting.tz.australia_sydney'    => 'Sydney (UTC+10/+11)',
    'admin.setting.tz.pacific_auckland'    => 'New Zealand (UTC+12/+13)',
    'admin.setting.tz.utc'                 => 'Coordinated Universal Time (UTC+0)',

    /* ---------- Dashboard ---------- */
    'admin.dashboard.greeting_morning'      => 'Good morning, %s!',
    'admin.dashboard.greeting_noon'         => 'Good afternoon, %s!',
    'admin.dashboard.greeting_night'        => 'Good evening, %s!',
    'admin.dashboard.welcome'               => 'Welcome to %s',
    'admin.dashboard.stat_posts'            => 'Total Posts',
    'admin.dashboard.stat_published'        => 'Published',
    'admin.dashboard.stat_pending_posts'    => 'Pending Posts',
    'admin.dashboard.stat_comments'         => 'Public Comments',
    'admin.dashboard.stat_pending_comments' => 'Pending Comments',
    'admin.dashboard.stat_users'            => 'Registered Users',
    'admin.dashboard.recent_logs'           => 'Recent Audit Logs',
    'admin.dashboard.goto_logs'             => 'Go to Audit Logs',

    /* ---------- Logs ---------- */
    'admin.log.col_time'     => 'Time',
    'admin.log.col_user'     => 'User',
    'admin.log.col_category' => 'Category',
    'admin.log.col_action'   => 'Action',
    'admin.log.col_result'   => 'Result',
    'admin.log.success'      => 'Success',
    'admin.log.fail'         => 'Fail',

    /* ---------- Posts ---------- */
    'admin.post.status_published' => 'Published',
    'admin.post.status_pending'   => 'Pending',
    'admin.post.status_draft'     => 'Draft',
    'admin.post.status_trash'     => 'Trash',
    'admin.post.type_all'         => 'All Content',
    'admin.post.type_post'        => 'Posts',
    'admin.post.type_page'        => 'Pages',
    'admin.post.add'              => 'New Post',
    'admin.post.col_title'        => 'Title',
    'admin.post.col_author'       => 'Author',
    'admin.post.col_category'     => 'Category',
    'admin.post.col_views'        => 'Views',
    'admin.post.col_updated'      => 'Updated At',
    'admin.post.badge_page'       => 'Page',
    'admin.post.badge_top'        => 'Pinned',
    'admin.post.approve'          => 'Approve',
    'admin.post.reject'           => 'Reject',
    'admin.post.pin'              => 'Pin',
    'admin.post.unpin'            => 'Unpin',
    'admin.post.restore'          => 'Restore',
    'admin.post.destroy'          => 'Delete Permanently',
    'admin.post.destroy_confirm'  => 'Permanently delete? This cannot be undone.',
    'admin.post.trash_confirm'    => 'Move to trash?',
    'admin.post.edit_title'       => 'Edit Post',
    'admin.post.opt_publish'      => 'Publish',
    'admin.post.opt_submit_review'=> 'Submit for Review',
    'admin.post.field_title'      => 'Title',
    'admin.post.field_slug'       => 'Slug (must not be purely numeric)',
    'admin.post.uncategorized'    => 'Uncategorized',
    'admin.post.as_page'          => 'As a standalone page (not listed among posts)',
    'admin.post.show_in_nav'      => 'Show in sidebar navigation',
    'admin.post.audit_hint'       => 'Post review is enabled: submitted posts are published only after admin approval.',
    'admin.post.field_content'    => 'Content (Markdown)',
    'admin.post.field_excerpt'    => 'Excerpt (optional; auto-generated if empty)',
    'admin.post.field_cover'      => 'Cover image (changed via upload only; jpg/png/webp/gif, max 2MB)',
    'admin.post.cover_preview'    => 'Cover preview',
    'admin.post.cover_upload'     => 'Upload Cover',
    'admin.post.top_only_published' => 'Only published posts can be pinned',
    'admin.post.top_done'         => 'Pinned; it will appear first in front-end lists',
    'admin.post.top_canceled'     => 'Unpinned',
    'admin.post.not_found'        => 'Post not found',
    'admin.post.title_required'   => 'Title is required',
    'admin.post.cover_invalid'    => 'Invalid cover path (only images under uploads/ are allowed)',
    'admin.post.slug_numeric'     => 'Slug must not be purely numeric to avoid conflicts with post-ID access',
    'admin.post.slug_taken'       => 'Slug is already taken',
    'admin.post.saved'            => 'Saved successfully',
    'admin.post.trashed'          => 'Moved to trash',
    'admin.post.restored'         => 'Restored to draft',
    'admin.post.destroyed'        => 'Permanently deleted',
    'admin.post.approved'         => 'Approved and published',
    'admin.post.rejected'         => 'Rejected to draft',

    /* ---------- Upload ---------- */
    'admin.upload.failed'   => 'Upload failed',
    'admin.upload.cover_ok' => 'Cover uploaded',

    /* ---------- Comments ---------- */
    'admin.comment.status_published' => 'Public',
    'admin.comment.status_pending'   => 'Pending',
    'admin.comment.status_trash'     => 'Trash',
    'admin.comment.filter_author'    => 'Author username/nickname or ID',
    'admin.comment.filter_post_id'   => 'Post ID',
    'admin.comment.filter_date_range'=> 'Date range',
    'admin.comment.filter_btn'       => 'Filter',
    'admin.comment.total'            => '%s comments in total.',
    'admin.comment.col_content'      => 'Content',
    'admin.comment.col_post'         => 'Post',
    'admin.comment.approved'         => 'Comment approved',
    'admin.comment.rejected'         => 'Comment rejected',
    'admin.comment.trashed'          => 'Comment moved to trash',
    'admin.comment.restored'         => 'Comment restored',
    'admin.comment.restored_pending' => 'Comment restored; it will be published after review',

    /* ---------- Categories ---------- */
    'admin.category.add'            => 'Add Category',
    'admin.category.name'           => 'Name',
    'admin.category.slug'           => 'Meaning (slug)',
    'admin.category.description'    => 'Description',
    'admin.category.sort'           => 'Sort',
    'admin.category.add_btn'        => 'Add',
    'admin.category.col_edit'       => 'Edit (name / slug / description / sort)',
    'admin.category.delete_confirm' => 'Delete this category?',
    'admin.category.name_required'  => 'Category name is required',
    'admin.category.slug_required'  => 'Slug is required (lowercase letters, digits, hyphens only)',
    'admin.category.slug_taken'     => 'Slug is already taken',
    'admin.category.in_use'         => 'This category still has %s posts; move them before deleting',
    'admin.category.deleted'        => 'Category deleted',

    /* ---------- Users ---------- */
    'admin.user.add'                   => 'New User',
    'admin.user.edit_title'            => 'Edit User',
    'admin.user.role_admin'            => 'Administrator',
    'admin.user.role_editor'           => 'Editor',
    'admin.user.role_user'             => 'User',
    'admin.user.col_username'          => 'Username',
    'admin.user.col_nickname'          => 'Nickname',
    'admin.user.col_email'             => 'Email',
    'admin.user.col_phone'             => 'Phone',
    'admin.user.col_role'              => 'Role',
    'admin.user.col_locked'            => 'Locked',
    'admin.user.col_registered'        => 'Registered At',
    'admin.user.me'                    => ' (me)',
    'admin.user.status_ok'             => 'Active',
    'admin.user.status_disabled'       => 'Disabled',
    'admin.user.status_banned'         => 'Banned',
    'admin.user.status_deleted'        => 'Deregistered',
    'admin.user.opt_disabled'          => 'Disabled',
    'admin.user.locked_until'          => 'Locked until %s',
    'admin.user.unlock'                => 'Unlock',
    'admin.user.ban'                   => 'Ban',
    'admin.user.unban'                 => 'Unban',
    'admin.user.deregister'            => 'Deregister',
    'admin.user.ban_confirm'           => 'The user will be unable to log in. Confirm ban?',
    'admin.user.deregister_confirm'    => 'The user will be unable to log in and their posts/comments will show as "Deregistered user". Confirm?',
    'admin.user.field_username_new'    => 'Username (3-32 letters/digits/underscore)',
    'admin.user.field_email'           => 'Email (optional)',
    'admin.user.field_phone'           => 'Phone (optional)',
    'admin.user.field_role'            => 'Role (editor/admin can only be granted by an administrator here)',
    'admin.user.root_no_demote'        => ' (root admin, cannot be demoted)',
    'admin.user.field_status'          => 'Account Status',
    'admin.user.field_new_password'    => 'Reset password (leave empty to keep; 8-64 chars, at least 3 of upper/lower/digit/special)',
    'admin.user.field_current_password'=> 'Your current password (required for resetting password or changing email/phone; sensitive-operation re-verification)',
    'admin.user.create_tip'            => 'A strong random initial password will be generated and shown only once after saving.',
    'admin.user.force_change'          => 'Force password change at next login (works with the periodic password change policy)',
    'admin.user.not_found'             => 'User not found',
    'admin.user.username_format'       => 'Username must be 3-32 letters, digits or underscores',
    'admin.user.username_taken'        => 'Username is already taken',
    'admin.user.email_taken'           => 'Email is already taken',
    'admin.user.phone_taken'           => 'Phone number is already taken',
    'admin.user.gen_pwd_error'         => 'Initial password generation error: %s',
    'admin.user.concurrent_conflict'   => 'Username/email/phone already taken (concurrent conflict), please retry',
    'admin.user.created_with_pwd'      => 'User created. Initial password (shown only once, share via a secure channel): %s',
    'admin.user.operator_pwd_required' => 'Resetting password or changing email/phone requires your (operator) current password',
    'admin.user.self_protect'          => 'You cannot disable or change the role of your own account',
    'admin.user.root_protect'          => 'The root administrator account cannot be demoted or disabled',
    'admin.user.last_admin'            => 'The system must keep at least one administrator',
    'admin.user.saved_pwd_reset'       => 'User saved; password reset',
    'admin.user.saved'                 => 'User saved',
    'admin.user.unlocked'              => 'Lock released',
    'admin.user.self_ban'              => 'You cannot ban yourself',
    'admin.user.root_ban'              => 'The root administrator account cannot be banned',
    'admin.user.last_admin_avail'      => 'The system must keep at least one available administrator',
    'admin.user.banned'                => 'User banned; they can no longer log in',
    'admin.user.unbanned'              => 'Ban lifted',
    'admin.user.self_deregister'       => 'You cannot deregister yourself',
    'admin.user.root_deregister'       => 'The root administrator account cannot be deregistered',
    'admin.user.deregistered'          => 'User deregistered; their past content will be anonymized as "Deregistered user"',
    'admin.user.restored'              => 'User restored',

    /* ---------- Navigation manager ---------- */
    // help contains a <code> tag (trusted core pack); the view outputs it unescaped
    'admin.nav.help'              => 'Drag the handle at the start of a row to reorder; items appear in the front-end navigation in the saved order. One level of nesting is supported: set a row\'s "Parent" to another row to make it a child (the parent must be an earlier top-level row); dragging does not change parent-child relations (a child cannot be dragged above its parent). New items must have a link; existing top-level items may leave the link empty later to act as a plain-text group label (effective only with children); child links are required. Click "Add Item" to append a row — if top-level items exist you can pick a parent right away; the red button at the end of a row removes it, and children of a removed parent are promoted to top level. All changes take effect after "Save". Links support in-site relative paths (e.g. <code>/index.php?r=page/about</code>) or http(s) URLs.',
    'admin.nav.drag'              => 'Drag to reorder',
    'admin.nav.top'               => 'Top level',
    'admin.nav.remove_row'        => 'Remove this row',
    'admin.nav.empty'             => 'No custom navigation items yet. Use the button below to add one.',
    'admin.nav.new_title'         => 'New item title (leave empty to skip)',
    'admin.nav.new_url'           => 'New link, e.g. /index.php?r=page/about',
    'admin.nav.new_badge'         => 'New (top level)',
    'admin.nav.add_btn'           => 'Add Item',
    'admin.nav.child_url_required'=> 'Child link required',
    'admin.nav.top_url_optional'  => 'Top level may stay empty as a group label',
    'admin.nav.new_url_required'  => 'Link (required), e.g. /index.php?r=page/about',

    /* ---------- Security settings ---------- */
    'admin.security.tip'                 => 'The defaults below match the baseline security level; lowering them weakens system security. All changes are written to the audit log.',
    'admin.security.group_login'         => 'Login & Session',
    'admin.security.group_password'      => 'Password Policy',
    'admin.security.group_ip'            => 'Client IP',
    'admin.security.group_log'           => 'Audit Log',
    'admin.security.group_debug'         => 'Debug',
    'admin.security.login_max_fail'      => 'Consecutive login failures before lockout (times, default 5)',
    'admin.security.lock_minutes'        => 'Lockout duration (minutes, default 10)',
    'admin.security.session_timeout'     => 'Session idle timeout (minutes, default 30)',
    'admin.security.pwd_expire'          => 'Enable periodic password change',
    'admin.security.pwd_expire_hint'     => 'Off by default; when enabled, overdue logins are forced to change password',
    'admin.security.pwd_expire_days'     => 'Password validity (days, 30-365, default 90)',
    'admin.security.pwd_history'         => 'Password history anti-reuse count (0 = off, default 0)',
    'admin.security.ip_header'           => 'Read client IP from a custom header',
    'admin.security.ip_header_hint'      => 'Off by default',
    'admin.security.ip_header_name'      => 'Header name(s) (comma-separated, earlier first; e.g. ali-real-client-ip,X-Forwarded-For)',
    'admin.security.ip_header_name_hint' => 'Headers are tried in order; the first valid IP wins. REMOTE_ADDR is used when none yields a valid IP.',
    'admin.security.ip_warn'             => 'Warning: enable this only when the site sits behind a trusted reverse proxy/CDN. If the server is directly exposed to the Internet while trusting headers like X-Forwarded-For, attackers can spoof IPs to bypass rate limiting and auditing.',
    'admin.security.log_retention'       => 'Log retention days (minimum 180, default 180)',
    'admin.security.debug'               => 'Debug mode',
    'admin.security.debug_hint'          => 'Must be off in production; when on, error details are printed to pages',

    /* ---------- Themes ---------- */
    'admin.theme.upload_title'      => 'Upload Theme (zip, must contain style.css)',
    'admin.theme.col_dir'           => 'Theme',
    'admin.theme.col_version'       => 'Version',
    'admin.theme.empty'             => 'No themes found',
    'admin.theme.active'            => 'Active',
    'admin.theme.inactive'          => 'Inactive',
    'admin.theme.configure'         => 'Settings',
    'admin.theme.delete_confirm'    => 'Delete this theme? This cannot be undone.',
    'admin.theme.not_found'         => 'Theme not found',
    'admin.theme.activated'         => 'Theme activated: %s',
    'admin.theme.not_deletable'     => 'This theme cannot be deleted',
    'admin.theme.cannot_delete_active' => 'Cannot delete the currently active theme',
    'admin.theme.deleted'           => 'Theme deleted',
    'admin.theme.dir_missing'       => 'Theme directory not found',
    'admin.theme.setting_page'      => 'Theme Settings',
    'admin.theme.setting_title'     => 'Theme Settings: %s (%s)',
    'admin.theme.no_schema'         => 'This theme provides no settings schema (no settings.php in its directory); nothing to configure.',
    'admin.theme.setting_saved'     => 'Theme settings saved',
    'admin.theme.zip_required'      => 'Please choose a zip file to upload',
    'admin.theme.zip_too_large'     => 'The zip file must not exceed 10MB',
    'admin.theme.zip_only'          => 'Only .zip format is supported',
    'admin.theme.zip_ext_missing'   => 'The ZipArchive extension is not enabled on the server; cannot extract theme packages',
    'admin.theme.dir_invalid'       => 'Theme directory name is invalid or reserved',
    'admin.theme.zip_open_failed'   => 'The zip file cannot be opened',
    'admin.theme.zip_bad_path'      => 'The zip contains illegal path entries',
    'admin.theme.zip_bad_entry'     => 'The zip contains a disallowed entry: %s',
    'admin.theme.zip_no_style'      => 'The theme package is missing style.css',
    'admin.theme.dir_create_failed' => 'Failed to create the theme directory',
    'admin.theme.zip_extract_failed'=> 'Failed to extract the zip',
    'admin.theme.uploaded'          => 'Theme uploaded: %s',
    'admin.theme.updated'           => 'Theme overwritten and updated: %s',
    'admin.theme.no_overwrite_active' => 'Cannot overwrite the currently active theme; please switch to another theme first',
    'admin.theme.name_mismatch'     => 'The Theme Name in the package does not match the existing theme; overwrite rejected',
    'admin.theme.upload_tip'        => 'A theme with the same name will be overwritten (old directory backed up automatically, rollback on failure); the active theme and default cannot be overwritten. Server upload limit approx. %sMB; program limit 10MB.',

    /* ---------- Plugins ---------- */
    'admin.plugin.orphan_tip'        => 'The directories of the following plugins no longer exist (possibly deleted directly instead of uninstalled), but their configuration and data remain in the database:',
    'admin.plugin.orphan_confirm'    => 'Clean up all residual data of this plugin? This cannot be undone.',
    'admin.plugin.orphan_btn'        => 'Clean Residual Data',
    'admin.plugin.col_name'          => 'Plugin',
    'admin.plugin.empty'             => 'No plugins found',
    'admin.plugin.active'            => 'Active',
    'admin.plugin.inactive'          => 'Inactive',
    'admin.plugin.delete_confirm'    => 'Delete this plugin? This cannot be undone.',
    'admin.plugin.orphan_none'       => 'Nothing to clean for this plugin, or its directory still exists',
    'admin.plugin.orphan_cleaned'    => 'Residual data cleaned: %s',
    'admin.plugin.activate_failed'   => 'Plugin not found or activation failed',
    'admin.plugin.activated'         => 'Plugin activated',
    'admin.plugin.deactivate_failed' => 'Plugin is not active or does not exist',
    'admin.plugin.deactivated'       => 'Plugin deactivated',
    'admin.plugin.uninstall_failed'  => 'Plugin not found or deletion failed',
    'admin.plugin.uninstalled'       => 'Plugin deleted',
    'admin.plugin.zip_required'      => 'Please select a zip file to upload',
    'admin.plugin.zip_no_main'       => 'Main file ({slug}.php) not found in the plugin package',
    'admin.plugin.main_file_invalid' => 'No valid plugin main file found in the package ({slug}.php with a Plugin Name header required)',
    'admin.plugin.name_mismatch'     => 'The Plugin Name in the package differs from the existing plugin; overwrite rejected',
    'admin.plugin.uploaded'          => 'Plugin uploaded: %s',
    'admin.plugin.updated'           => 'Plugin overwritten and updated: %s',
    'admin.plugin.upload_title'      => 'Upload plugin (zip; the package must contain a {slug}.php main file declaring Plugin Name)',
    'admin.plugin.upload_tip'        => 'A plugin with the same name will be overwritten (old directory backed up automatically, rollback on failure). Server upload limit approx. %sMB; program limit 10MB.',

    /* ---------- Audit log center (extra) ---------- */
    'admin.log.all_categories'  => 'All categories',
    'admin.log.all_results'     => 'All results',
    'admin.log.keyword_ph'      => 'Action keyword',
    'admin.log.date_range_ph'   => 'Start date ~ End date',
    'admin.log.export_confirm'  => 'Exporting audit logs requires your current login password. Continue?',
    'admin.log.export_pwd_ph'   => 'Current password (required for export)',
    'admin.log.export_btn'      => 'Export CSV',
    'admin.log.total'           => '%s records in total.',
    'admin.log.col_operator'    => 'Operator',
    'admin.log.col_detail'      => 'Detail',
    'admin.log.csv_user_id'     => 'User ID',
    'admin.log.export_pwd_wrong'=> 'Exporting audit logs requires a correct current password',

    /* ---------- Profile ---------- */
    'admin.profile.basic'              => 'Basic Profile',
    'admin.profile.signature'          => 'Signature (shown under the nickname on the author page; up to 100 chars; empty = hidden)',
    'admin.profile.email_code'         => 'Email verification code (only needed when changing email)',
    'admin.profile.sms_code'           => 'SMS verification code (only needed when changing phone)',
    'admin.profile.send_code'          => 'Send Code',
    'admin.profile.avatar'             => 'Avatar (changed via upload only; jpg/png/webp/gif, max 1MB)',
    'admin.profile.avatar_preview'     => 'Avatar preview',
    'admin.profile.avatar_upload'      => 'Upload Avatar',
    'admin.profile.current_pwd'        => 'Current password (only needed when changing email/phone)',
    'admin.profile.change_pwd_card'    => 'Change Password',
    'admin.profile.goto_change_pwd'    => 'Go to Change Password',
    'admin.profile.pwd_expired_notice' => 'Your password has expired. You must change it before continuing to use the admin.',
    'admin.profile.old_pwd'            => 'Current Password',
    'admin.profile.new_pwd'            => 'New password (8-64 chars; at least 3 of upper/lower/digit/special; must not contain the username)',
    'admin.profile.confirm_pwd'        => 'Confirm New Password',
    'admin.profile.confirm_btn'        => 'Confirm Change',
    'admin.profile.avatar_invalid'     => 'Invalid avatar path',
    'admin.profile.pwd_required'       => 'Changing email/phone requires a correct current password',
    'admin.profile.email_code_wrong'   => 'Email verification code is wrong or expired',
    'admin.profile.sms_code_wrong'     => 'SMS verification code is wrong or expired',
    'admin.profile.phone_taken'        => 'This phone number is used by another account',
    'admin.profile.saved'              => 'Profile saved',
    'admin.profile.pwd_mismatch'       => 'The two new password entries do not match',
    'admin.profile.pwd_changed'        => 'Password changed successfully',

    /* ---------- Upload (extra) ---------- */
    'admin.upload.image_size'     => 'Image must be within 2MB',
    'admin.upload.avatar_size'    => 'Avatar must be within 1MB',
    'admin.upload.no_file'        => 'No file received',
    'admin.upload.error_code'     => 'Upload failed (error code %s)',
    'admin.upload.mime_whitelist' => 'Only jpg/png/webp/gif images are supported',
    'admin.upload.dir_failed'     => 'Failed to create the upload directory',
    'admin.upload.save_failed'    => 'Failed to save the file',
    'admin.upload.avatar_ok'      => 'Avatar uploaded',

    /* ---------- JS interaction strings (injected into admin.js / verify.js / password_check.js / nav_sort.js) ---------- */
    'admin.js.confirm_title'      => 'Confirmation',
    'admin.js.confirm_ok'         => 'Confirm',
    'admin.verify.fill_target'    => 'Please enter an email or phone number first',
    'admin.verify.network_error'  => 'Network error, please retry',
    'admin.verify.retry_in'       => 'Resend in %s s',
    'admin.pwd.need'              => 'Please enter a new password',
    'admin.pwd.len'               => 'Password must be 8-64 characters',
    'admin.pwd.classes'           => 'Password must contain at least 3 of: uppercase, lowercase, digit, special character',
    'admin.pwd.contain_name'      => 'Password must not contain the username',
    'admin.pwd.repeat'            => 'Please enter the new password again',
    'admin.pwd.mismatch'          => 'The two password entries do not match',
    'admin.pwd.mismatch_live'     => 'Entries do not match',
    'admin.pwd.match_ok'          => 'Entries match ✓',
    'admin.nav.max_tip'           => 'At most %s navigation items',
);
