<?php
/**
 * 默认主题英文语言包：缺键自动回退主题中文基线（langs/zh_CN.php）
 * 键清单以中文基线包为准；下划线前缀键（_name/_locale）为包元信息
 */
defined('APP_BOOT') or exit;

return array(
    '_name'   => 'English',
    '_locale' => 'en-US',

    /* ---------- Common (list/toolbar/pagination) ---------- */
    'theme.common.date_format'     => 'M j, Y',
    'theme.common.read_count'      => '%s views',
    'theme.common.top_badge'       => 'Top',
    'theme.common.read_more'       => 'Read more',
    'theme.common.page_prev'       => 'Previous',
    'theme.common.page_next'       => 'Next',
    'theme.common.back'            => 'Back',
    'theme.common.toc'             => 'Table of contents',
    'theme.common.toc_short'       => 'Contents',
    'theme.common.font_decrease'   => 'Decrease font size',
    'theme.common.font_increase'   => 'Increase font size',
    'theme.common.print_article'   => 'Print article',
    'theme.common.print_page'      => 'Print page',
    'theme.common.back_to_top'     => 'Back to top',
    'theme.common.toggle_menu'     => 'Toggle menu',
    'theme.common.darkmode'        => 'Toggle dark mode',
    'theme.common.confirm_default' => 'Are you sure you want to proceed?',
    'theme.common.empty_posts'     => 'No posts yet.',
    'theme.common.empty_archive'   => 'No posts in this archive yet.',

    /* ---------- Sidebar ---------- */
    'theme.sidebar.dashboard'          => 'Dashboard',
    'theme.sidebar.login'              => 'Log in',
    'theme.sidebar.register'           => 'Register',
    'theme.sidebar.search_label'       => 'Search: ',
    'theme.sidebar.search_placeholder' => 'Search...',
    'theme.sidebar.nav'                => 'Navigation',
    'theme.sidebar.home'               => 'Home',
    'theme.sidebar.category'           => 'Categories',
    'theme.sidebar.language'           => 'Language',

    /* ---------- Footer ---------- */
    'theme.footer.admin'    => 'Admin panel',
    'theme.footer.logout'   => 'Log out',
    'theme.footer.login'    => 'Log in',
    'theme.footer.register' => 'Register',

    /* ---------- Post detail ---------- */
    'theme.post.unpublished_preview' => 'Unpublished preview',

    /* ---------- Comments ---------- */
    'theme.comment.title'            => 'Comments (%s)',
    'theme.comment.empty'            => 'No comments yet.',
    'theme.comment.save'             => 'Save',
    'theme.comment.cancel'           => 'Cancel',
    'theme.comment.edit'             => 'Edit',
    'theme.comment.delete'           => 'Delete',
    'theme.comment.delete_confirm'   => 'Delete this comment?',
    'theme.comment.pending_badge'    => 'Pending',
    'theme.comment.form_title'       => 'Leave a comment',
    'theme.comment.placeholder'      => 'Write your comment…',
    'theme.comment.submit'           => 'Submit comment',
    // %s is the login link (safe HTML built by the template)
    'theme.comment.login_to_comment' => 'Please %s to comment.',
    'theme.comment.login_link'       => 'log in',

    /* ---------- Search page ---------- */
    'theme.search.title'         => 'Search',
    'theme.search.title_with_kw' => 'Search: %s',
    'theme.search.result_count'  => '%s post(s) found',
    'theme.search.empty'         => 'No matching posts found.',

    /* ---------- 404 ---------- */
    'theme.notfound.message'   => 'The page does not exist or has been removed.',
    'theme.notfound.back_home' => 'Back to home',

    /* ---------- Auth pages (login/register/password reset) ---------- */
    'theme.auth.login_title'        => 'Log in',
    'theme.auth.account'            => 'Username or email',
    'theme.auth.password'           => 'Password',
    'theme.auth.login_submit'       => 'Log in',
    'theme.auth.forgot_link'        => 'Forgot password?',
    'theme.auth.register_link'      => 'Create an account',
    'theme.auth.register_title'     => 'Register',
    'theme.auth.username_label'     => 'Username (3-32 letters, digits or underscores)',
    'theme.auth.nickname_label'     => 'Nickname (optional)',
    'theme.auth.email'              => 'Email',
    'theme.auth.email_code'         => 'Email verification code',
    'theme.auth.send_code'          => 'Send code',
    'theme.auth.phone'              => 'Phone',
    'theme.auth.optional'           => ' (optional)',
    'theme.auth.sms_code'           => 'SMS verification code',
    'theme.auth.pwd_rule_len'       => '8-64 characters',
    'theme.auth.pwd_rule_upper'     => 'Contains uppercase letters',
    'theme.auth.pwd_rule_lower'     => 'Contains lowercase letters',
    'theme.auth.pwd_rule_digit'     => 'Contains digits',
    'theme.auth.pwd_rule_special'   => 'Contains special characters',
    'theme.auth.pwd_rule_classes'   => 'At least 3 of the 4 types above',
    'theme.auth.pwd_rule_username'  => 'Does not contain the username',
    'theme.auth.confirm_password'   => 'Confirm password',
    'theme.auth.register_submit'    => 'Register',
    'theme.auth.has_account'        => 'Already have an account? ',
    'theme.auth.login_now'          => 'Log in',
    'theme.auth.forgot_title'       => 'Reset password',
    'theme.auth.forgot_hint'        => 'Enter your username to receive a code via your bound phone, or your email to receive a code by email',
    'theme.auth.code'               => 'Verification code',
    'theme.auth.new_password_label' => 'New password (8-64 chars; at least 3 of uppercase/lowercase/digit/special; must not contain the username)',
    'theme.auth.confirm_new_password' => 'Confirm new password',
    'theme.auth.reset_submit'       => 'Reset password',
    'theme.auth.no_provider'        => 'No email or SMS verification plugin is enabled; password cannot be reset online. Please contact the administrator.',
    'theme.auth.back_login'         => 'Back to login',

    /* ---------- Theme JS messages (register_check.js / kernel verify.js / password_check.js overrides) ---------- */
    'theme.js.verify_fill_target'   => 'Please enter your email or phone number first',
    'theme.js.verify_network_error' => 'Network error, please try again',
    'theme.js.verify_retry_in'      => 'Resend in %s s',
    'theme.js.verify_send'          => 'Send code',
    'theme.js.pwd_need'             => 'Please enter a new password',
    'theme.js.pwd_len'              => 'Password must be 8-64 characters',
    'theme.js.pwd_classes'          => 'Password must contain at least 3 of: uppercase, lowercase, digits, special characters',
    'theme.js.pwd_contain_name'     => 'Password must not contain the username',
    'theme.js.pwd_match_ok'         => 'Passwords match ✓',
    'theme.js.pwd_mismatch_live'    => 'Passwords do not match',
    'theme.js.pwd_repeat'           => 'Please enter the new password again',
    'theme.js.pwd_mismatch'         => 'The two passwords do not match',
    'theme.js.reg_need_password'    => 'Please enter a password',
    'theme.js.reg_need_username'    => 'Please enter a username',
    'theme.js.reg_username_invalid' => 'Username must be 3-32 letters, digits or underscores',
    'theme.js.reg_email_invalid'    => 'Invalid email format',
    'theme.js.reg_need_email_code'  => 'Please enter the email verification code',
    'theme.js.reg_need_phone'       => 'Please enter your phone number',
    'theme.js.reg_phone_invalid'    => 'Invalid phone number format',
    'theme.js.reg_need_sms_code'    => 'Please enter the SMS verification code',
    'theme.js.reg_need_password2'   => 'Please enter the password again',

    /* ---------- Front controller messages (Front.php: flash/form errors/page titles/AJAX) ---------- */
    'theme.front.deleted_user'           => 'Deleted user',
    'theme.front.unknown_user'           => 'Unknown',
    'theme.front.default_nickname'       => 'User',
    'theme.front.category_title'         => 'Category: %s',
    'theme.front.search_title'           => 'Search',
    'theme.front.login_title'            => 'Log in',
    'theme.front.register_title'         => 'Register',
    'theme.front.forgot_title'           => 'Reset password',
    'theme.front.notfound_title'         => 'Page not found',
    'theme.front.login_empty'            => 'Please enter your account and password',
    'theme.front.login_required'         => 'Please log in',
    'theme.front.register_closed'        => 'Public registration is closed. Please contact the administrator if you need an account.',
    'theme.front.throttled'              => 'Too many attempts, please try again later',
    /* The following 12 keys map to Auth::msgOf machine codes */
    'theme.front.auth.throttled'          => 'Too many attempts, please try again later',
    'theme.front.auth.invalid_credentials' => 'Incorrect account or password',
    'theme.front.auth.locked'             => 'Too many failed attempts; account locked for %s minutes',
    'theme.front.auth.login_success'      => 'Login successful',
    'theme.front.auth.pwd_len'            => 'Password must be 8-64 characters',
    'theme.front.auth.pwd_classes'        => 'Password must contain at least 3 of: uppercase letters, lowercase letters, digits, special characters',
    'theme.front.auth.pwd_contain_name'   => 'Password must not contain the username',
    'theme.front.auth.pwd_weak'           => 'Password is too simple (weak password blacklist hit)',
    'theme.front.auth.user_not_found'     => 'User not found',
    'theme.front.auth.old_password_wrong' => 'Current password is incorrect',
    'theme.front.auth.pwd_history_hit'    => 'New password cannot be the same as any of the last %s passwords',
    'theme.front.auth.pwd_changed'        => 'Password changed successfully',
    'theme.front.username_invalid'       => 'Username must be 3-32 letters, digits or underscores',
    'theme.front.username_taken'         => 'Username is already taken',
    'theme.front.email_taken'            => 'Email is already registered',
    'theme.front.phone_taken'            => 'Phone number is already registered',
    'theme.front.password_mismatch'      => 'The two passwords do not match',
    'theme.front.email_code_invalid'     => 'Email verification code is incorrect or expired',
    'theme.front.phone_required'         => 'Please enter your phone number',
    'theme.front.sms_code_invalid'       => 'SMS verification code is incorrect or expired',
    'theme.front.register_success'       => 'Registration successful, please log in',
    'theme.front.forgot_no_provider'     => 'No email or SMS verification plugin is enabled. Please contact the administrator to reset your password.',
    'theme.front.new_password_mismatch'  => 'The two new passwords do not match',
    'theme.front.reset_generic'          => 'If the account exists and the information is correct, the password will be reset',
    'theme.front.reset_success'          => 'Password has been reset. Please log in with the new password',
    'theme.front.comment_login_required' => 'Please log in before commenting',
    'theme.front.comment_login_operate'  => 'Please log in before managing comments',
    'theme.front.post_not_found'         => 'Post not found',
    'theme.front.comment_closed'         => 'Comments are closed for this post',
    'theme.front.comment_empty'          => 'Comment content cannot be empty',
    'theme.front.comment_blocked'        => 'Comment was blocked',
    'theme.front.comment_pending'        => 'Comment submitted, awaiting review',
    'theme.front.comment_success'        => 'Comment posted',
    'theme.front.comment_not_found'      => 'Comment not found',
    'theme.front.comment_edit_own'       => 'You can only edit your own comments',
    'theme.front.comment_delete_own'     => 'You can only delete your own comments',
    'theme.front.comment_updated_pending' => 'Comment updated, will appear after review',
    'theme.front.comment_updated'        => 'Comment updated',
    'theme.front.comment_has_replies'    => 'This comment has replies and cannot be deleted',
    'theme.front.comment_deleted'        => 'Comment deleted',
    'theme.front.verify_param_incomplete' => 'Incomplete parameters',
    'theme.front.verify_sent'            => 'Verification code sent',
    'theme.front.verify_channel_off'     => 'No verification plugin is enabled for this channel',
    'theme.front.verify_retry'           => 'Sending too frequently, please retry in 60 seconds',
    'theme.front.verify_daily_limit'     => 'Daily sending limit reached',
    'theme.front.verify_unavailable'     => 'Sending channel unavailable',
);
