<?php
/**
 * 默认主题中文基线语言包：随主题发布，作为主题内所有语言的最终降级方案，禁止删除
 * 键规范：theme.{模块}.{语义}；下划线前缀键（_name/_locale）为包元信息
 */
defined('APP_BOOT') or exit;

return array(
    '_name'   => '中文（简体）',
    '_locale' => 'zh-CN',

    /* ---------- 通用（列表/工具栏/分页） ---------- */
    // 日期格式串（date() 语法），英文包应覆盖为 'M j, Y' 之类
    'theme.common.date_format'     => 'Y 年 n 月 j 日',
    'theme.common.read_count'      => '阅读 %s',
    'theme.common.top_badge'       => '置顶',
    'theme.common.read_more'       => '继续阅读',
    'theme.common.page_prev'       => '上一页',
    'theme.common.page_next'       => '下一页',
    'theme.common.back'            => '返回上一页',
    'theme.common.toc'             => '文章目录',
    'theme.common.toc_short'       => '目录',
    'theme.common.font_decrease'   => '缩小字号',
    'theme.common.font_increase'   => '放大字号',
    'theme.common.print_article'   => '打印文章',
    'theme.common.print_page'      => '打印页面',
    'theme.common.back_to_top'     => '回到顶部',
    'theme.common.toggle_menu'     => '切换菜单',
    'theme.common.darkmode'        => '切换暗色模式',
    'theme.common.confirm_default' => '确认执行该操作？',
    'theme.common.empty_posts'     => '暂无文章。',
    'theme.common.empty_archive'   => '该归档下暂无文章。',

    /* ---------- 侧边栏 ---------- */
    'theme.sidebar.dashboard'          => '仪表盘',
    'theme.sidebar.login'              => '登录',
    'theme.sidebar.register'           => '注册',
    'theme.sidebar.search_label'       => '搜索：',
    'theme.sidebar.search_placeholder' => '搜索...',
    'theme.sidebar.nav'                => '导航',
    'theme.sidebar.home'               => '首页',
    'theme.sidebar.category'           => '分类',
    'theme.sidebar.language'           => '语言',

    /* ---------- 页脚 ---------- */
    'theme.footer.admin'    => '进入后台',
    'theme.footer.logout'   => '登出',
    'theme.footer.login'    => '登录',
    'theme.footer.register' => '注册',

    /* ---------- 文章详情 ---------- */
    'theme.post.unpublished_preview' => '未发布预览',

    /* ---------- 评论区 ---------- */
    'theme.comment.title'           => '评论 (%s)',
    'theme.comment.empty'           => '暂无评论。',
    'theme.comment.save'            => '保存',
    'theme.comment.cancel'          => '取消',
    'theme.comment.edit'            => '编辑',
    'theme.comment.delete'          => '删除',
    'theme.comment.delete_confirm'  => '确认删除这条评论？',
    'theme.comment.pending_badge'   => '待审核',
    'theme.comment.form_title'      => '发表评论',
    'theme.comment.placeholder'     => '写下你的评论…',
    'theme.comment.submit'          => '提交评论',
    // %s 为登录链接（模板拼入安全 HTML），英文语序不同可自行移动占位
    'theme.comment.login_to_comment' => '%s 后才可以发表评论。',
    'theme.comment.login_link'       => '登录',

    /* ---------- 搜索页 ---------- */
    'theme.search.title'         => '搜索',
    'theme.search.title_with_kw' => '搜索：%s',
    'theme.search.result_count'  => '共找到 %s 篇相关文章',
    'theme.search.empty'         => '没有找到相关文章。',

    /* ---------- 404 ---------- */
    'theme.notfound.message'   => '页面不存在或已被移除。',
    'theme.notfound.back_home' => '返回首页',

    /* ---------- 认证页（登录/注册/找回密码） ---------- */
    'theme.auth.login_title'        => '登录',
    'theme.auth.account'            => '用户名或邮箱',
    'theme.auth.password'           => '密码',
    'theme.auth.login_submit'       => '登录',
    'theme.auth.forgot_link'        => '忘记密码？',
    'theme.auth.register_link'      => '注册新账号',
    'theme.auth.register_title'     => '注册',
    'theme.auth.username_label'     => '用户名（3-32 位字母/数字/下划线）',
    'theme.auth.nickname_label'     => '昵称（可选）',
    'theme.auth.email'              => '邮箱',
    'theme.auth.email_code'         => '邮箱验证码',
    'theme.auth.send_code'          => '发送验证码',
    'theme.auth.phone'              => '手机号',
    'theme.auth.optional'           => '（可选）',
    'theme.auth.sms_code'           => '短信验证码',
    'theme.auth.pwd_rule_len'       => '长度 8-64 位',
    'theme.auth.pwd_rule_upper'     => '包含大写字母',
    'theme.auth.pwd_rule_lower'     => '包含小写字母',
    'theme.auth.pwd_rule_digit'     => '包含数字',
    'theme.auth.pwd_rule_special'   => '包含特殊字符',
    'theme.auth.pwd_rule_classes'   => '上述四类至少满足三类',
    'theme.auth.pwd_rule_username'  => '不包含用户名',
    'theme.auth.confirm_password'   => '确认密码',
    'theme.auth.register_submit'    => '注册',
    'theme.auth.has_account'        => '已有账号？',
    'theme.auth.login_now'          => '直接登录',
    'theme.auth.forgot_title'       => '找回密码',
    'theme.auth.forgot_hint'        => '输入用户名时通过绑定手机发送短信；输入邮箱时通过邮箱发送验证码',
    'theme.auth.code'               => '验证码',
    'theme.auth.new_password_label' => '新密码（8-64 位；大写字母/小写字母/数字/特殊字符至少三类；不得含用户名）',
    'theme.auth.confirm_new_password' => '确认新密码',
    'theme.auth.reset_submit'       => '重置密码',
    'theme.auth.no_provider'        => '站点未启用邮箱或短信验证插件，无法在线找回密码，请联系管理员。',
    'theme.auth.back_login'         => '返回登录',

    /* ---------- 主题 JS 文案（register_check.js / 内核 verify.js / password_check.js 覆盖） ---------- */
    'theme.js.verify_fill_target'   => '请先填写邮箱或手机号',
    'theme.js.verify_network_error' => '网络异常，请重试',
    'theme.js.verify_retry_in'      => '%s 秒后重发',
    'theme.js.verify_send'          => '发送验证码',
    'theme.js.pwd_need'             => '请输入新密码',
    'theme.js.pwd_len'              => '密码长度须为 8-64 位',
    'theme.js.pwd_classes'          => '密码须包含大写/小写/数字/特殊字符中的至少三类',
    'theme.js.pwd_contain_name'     => '密码不得包含用户名',
    'theme.js.pwd_match_ok'         => '两次输入一致 ✓',
    'theme.js.pwd_mismatch_live'    => '两次输入不一致',
    'theme.js.pwd_repeat'           => '请再次输入新密码',
    'theme.js.pwd_mismatch'         => '两次输入的密码不一致',
    'theme.js.reg_need_password'    => '请输入密码',
    'theme.js.reg_need_username'    => '请输入用户名',
    'theme.js.reg_username_invalid' => '用户名为 3-32 位字母、数字或下划线',
    'theme.js.reg_email_invalid'    => '邮箱格式不正确',
    'theme.js.reg_need_email_code'  => '请填写邮箱验证码',
    'theme.js.reg_need_phone'       => '请输入手机号',
    'theme.js.reg_phone_invalid'    => '手机号格式不正确',
    'theme.js.reg_need_sms_code'    => '请填写短信验证码',
    'theme.js.reg_need_password2'   => '请再次输入密码',

    /* ---------- 前台控制器消息（Front.php：flash/表单错误/页面标题/AJAX 提示） ---------- */
    'theme.front.deleted_user'           => '用户已注销',
    'theme.front.unknown_user'           => '未知',
    'theme.front.default_nickname'       => '用户',
    'theme.front.category_title'         => '分类：%s',
    'theme.front.search_title'           => '搜索',
    'theme.front.login_title'            => '登录',
    'theme.front.register_title'         => '注册',
    'theme.front.forgot_title'           => '找回密码',
    'theme.front.notfound_title'         => '页面不存在',
    'theme.front.login_empty'            => '请输入账号和密码',
    'theme.front.login_required'         => '请先登录',
    'theme.front.register_closed'        => '本站已关闭公开注册，如需账号请联系管理员',
    'theme.front.throttled'              => '操作过于频繁，请稍后再试',
    /* 以下 12 键对应 Auth::msgOf 机器码（内核调用带中文缺省，此处覆写以支持主题语言） */
    'theme.front.auth.throttled'          => '操作过于频繁，请稍后再试',
    'theme.front.auth.invalid_credentials' => '账号或密码错误',
    'theme.front.auth.locked'             => '连续失败次数过多，账号已锁定 %s 分钟',
    'theme.front.auth.login_success'      => '登录成功',
    'theme.front.auth.pwd_len'            => '密码长度必须为 8-64 位',
    'theme.front.auth.pwd_classes'        => '密码必须包含大写字母、小写字母、数字、特殊字符中的至少三类',
    'theme.front.auth.pwd_contain_name'   => '密码中不得包含用户名',
    'theme.front.auth.pwd_weak'           => '密码过于简单，命中弱口令黑名单',
    'theme.front.auth.user_not_found'     => '用户不存在',
    'theme.front.auth.old_password_wrong' => '原密码错误',
    'theme.front.auth.pwd_history_hit'    => '新密码不能与最近 %s 次密码相同',
    'theme.front.auth.pwd_changed'        => '密码修改成功',
    'theme.front.username_invalid'       => '用户名为 3-32 位字母、数字或下划线',
    'theme.front.username_taken'         => '用户名已被占用',
    'theme.front.email_taken'            => '邮箱已被注册',
    'theme.front.phone_taken'            => '该手机号已被注册',
    'theme.front.password_mismatch'      => '两次输入的密码不一致',
    'theme.front.email_code_invalid'     => '邮箱验证码错误或已过期',
    'theme.front.phone_required'         => '请输入手机号',
    'theme.front.sms_code_invalid'       => '短信验证码错误或已过期',
    'theme.front.register_success'       => '注册成功，请登录',
    'theme.front.forgot_no_provider'     => '站点未启用邮箱或短信验证插件，请联系管理员重置密码。',
    'theme.front.new_password_mismatch'  => '两次输入的新密码不一致',
    'theme.front.reset_generic'          => '若账号存在且信息正确，密码将被重置',
    'theme.front.reset_success'          => '密码已重置，请使用新密码登录',
    'theme.front.comment_login_required' => '请先登录后再发表评论',
    'theme.front.comment_login_operate'  => '请先登录后再操作评论',
    'theme.front.post_not_found'         => '文章不存在',
    'theme.front.comment_closed'         => '该文章已关闭评论功能',
    'theme.front.comment_empty'          => '评论内容不能为空',
    'theme.front.comment_blocked'        => '评论被拦截',
    'theme.front.comment_pending'        => '评论已提交，等待审核',
    'theme.front.comment_success'        => '评论发表成功',
    'theme.front.comment_not_found'      => '评论不存在',
    'theme.front.comment_edit_own'       => '只能修改自己发表的评论',
    'theme.front.comment_delete_own'     => '只能删除自己发表的评论',
    'theme.front.comment_updated_pending' => '评论已修改，待审核后显示',
    'theme.front.comment_updated'        => '评论已修改',
    'theme.front.comment_has_replies'    => '该评论存在回复，无法删除',
    'theme.front.comment_deleted'        => '评论已删除',
    'theme.front.verify_param_incomplete' => '参数不完整',
    'theme.front.verify_sent'            => '验证码已发送',
    'theme.front.verify_channel_off'     => '该渠道未启用验证码插件',
    'theme.front.verify_retry'           => '发送过于频繁，请 60 秒后重试',
    'theme.front.verify_daily_limit'     => '今日发送次数已达上限',
    'theme.front.verify_unavailable'     => '发送渠道不可用',
);
